### PR TITLE
Introduce helper functions, setting and setting_update

### PR DESCRIPTION
**Pull request by amrography**
New `setting()` and `setting_update()` helper functions. I created new `src/helpers.php` and added it to `composer.json` autoload.

### setting()

Get setting value from setting class, example:

```php
$app_name = setting('general', 'app_name');

//with fallback (optional)
$app_name = setting('general', 'app_name', 'fallback_value');
```

### setting_update()

Update setting value in setting class, example:

```php
// @returns GeneralSettings
$generalClass = setting_update('general', 'app_name', 'My website');
```

You may update multiple keys too, example:

```php
// @returns GeneralSettings
$generalClass = setting_update('general', [
    'app_name' => 'My website'
    'colors' => ['red', 'orange']
]);
```

## Testing

I added test file class `HelpersTest` under namespace `Spatie\LaravelSettings\Tests\Support`, and tests ran successfully.

### CODE REVIEW

**Comment by ragingdave** [comment]
Wouldn't it make more sense to just use a similar usage approach as for example the config helper in laravel and just have one helper function?
As an example, your getter would remain the same, but the update would just be like:

```
setting('general', ['app_name' => 'My website']);

// OR

setting('general', [
    'app_name' => 'My website'
    'colors' => ['red', 'orange']
]);
```

Additionally, what is the expected return value here? The actual updatePayload and createPayload are void functions, so wouldn't it make more sense to have them stay that way?

In a completely different aspect, should packages even have such a common name for a global helper method. Admittedly, `setting` would have been my first choice as well, but is it possible to pollute the global namespace with just a generic helper method? Perhaps `sp_setting` could be a less generic global method that would still convey the method meaning while staying more specific to the package itself?

**Comment by amrography** [comment]
`setting()` function is not returning an instance of the **SettingClass**. It returns the **payload** only like following:
```php
...
$key = 'app_name';
return app(SettingClass::class)->$key; // 'My website'
...
```

To set the variables during runtime using `setting('general', ['app_name' => 'My website']);` was not on my plan. I might be later working on it.

The purpose of `setting()` and `setting_update()` functions are quick implementation in your app. If you have the same functions so the logic might be different and you don't need these helper functions.

**Comment by rubenvanassche** [comment]
I don't think we want to add this kind of functionality to the package, let me explain. This package was built around the idea to store settings with type safety, that's where the Settings classes come in. The group name you're using to update/load settings shouldn't be used when working with settings, its just an identifier to group settings within the database/Redis repo. The function `get_setting_group_class` is also a bit vague, what if someone calls their settings class `GeneralConfiguration`, we're also not exactly sure if the name of the settings group will always map onto the settings class.

In my opinion I would structure an helper method api as such, like @ragingdave said:

```php
// Fetch property from GeneralSettings
settings(GeneralSettings::class, 'property');

// Fetch property from GeneralSettings with a default value
settings(GeneralSettings::class, 'property', 'default_value');

// Set a property in GeneralSettings
settings(GeneralSettings::class, ['property'  => 'alpha']);
```

Since we're using a class name here, faking settings now will also work out of the box which is a nice to have.

**Comment by amrography** [comment]
I think It's usage only for my specific project. Thank you for your time.

**Pull request closed without merging**
