### PR TITLE
Add support for laravel 11

### PR DESCRIPTION
**Pull request by shuvroroy**

### CODE REVIEW

**Comment by rubenvanassche** [comment]
Looks like the tests are failing

**Comment by shuvroroy** [comment]
@rubenvanassche it will be fixed now 🤞

**Comment by Nielsvanpach** [comment]
Still failing. 
Could you get this working locally first before pushing?

**Comment by shuvroroy** [comment]
> Still failing. Could you get this working locally first before pushing?

@Nielsvanpach it's depend on laravel-data package and it's not have laravel 11 supported yet. [PR](https://github.com/spatie/laravel-data/pull/657) that solves this issue

**Comment by rubenvanassche** [comment]
Thanks

**Pull request merged**
