### PR TITLE
using `app` fn to resolve dep

### PR DESCRIPTION
**Pull request by suabahasa**
using `app` fn to resolve dep

#12

### CODE REVIEW

**Comment by suabahasa** [comment]
@rubenvanassche 
Can we to not strong typed the `Spatie\LaravelSettings\SettingsContainer::$app` for Lumen framework compatibility?

Since we can't use the PHP 8's union type, which not backward compatibility.

**Comment by rubenvanassche** [comment]
> Can we to not strong typed the Spatie\LaravelSettings\SettingsContainer::$app for Lumen framework compatibility?

Yeah that's good for me, could you type it as a union type in the docblock?

**Comment by rubenvanassche** [comment]
Looks like some tests are failing, could you check this please?

**Comment by rubenvanassche** [comment]
This should be fixed within v2

**Pull request closed without merging**
